apiVersion: v1
kind: Service
metadata:
  name: institucional-backend
  namespace: institucional
spec:
  selector:
    app: institucional-backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
