apiVersion: apps/v1
kind: Deployment
metadata:
  name: institucional-frontend
  namespace: institucional
  labels:
    app: institucional-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: institucional-frontend
  template:
    metadata:
      labels:
        app: institucional-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jlayoc/institucional-frontend:latest
          ports:
            - containerPort: 80
