apiVersion: v1
kind: Service
metadata:
  name: institucional-frontend
  namespace: institucional
spec:
  selector:
    app: institucional-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
