name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---------- FRONTEND ----------
      - name: Build Frontend Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/institucional-frontend:latest ./frontend

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Frontend image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/institucional-frontend:latest

      # ---------- BACKEND ----------
      - name: Build Backend Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/institucional-backend:latest ./backend

      - name: Push Backend image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/institucional-backend:latest
